#Thank you chatGPT
name: Update dev Tag

on:
  push:
    branches:
      - main  # Or any branch you want to trigger the action on

jobs:
  update-dev-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete existing 'dev' tag locally if exists
        run: |
          if git rev-parse dev >/dev/null 2>&1; then
            git tag -d dev
          fi

      - name: Delete 'dev' tag remotely if exists
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/dev"; then
            git push origin :refs/tags/dev
          fi

      - name: Create new 'dev' tag on the dev commit
        run: |
          git tag dev
          git push origin dev